version: "3.8"

services:
  localstack:
    container_name: "BASE-LOCALSTACK"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_NAME=test-lambda
      - BUCKET_NAME=test-bucket
      - SNS_TOPIC=test-topic
      - QUEUE_NAME=test-queue
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./aws:/etc/localstack/init/ready.d
      - ./aws/assets:/etc/assets
  cloud_storage:
    container_name: "gcp-storage-emulator"
    build:
      context: .
      dockerfile: gcp.Dockerfile
    ports:
      - 8080:8080
    environment:
      - BUCKET_NAME=infograficos-estaticos
    
