name: CI/CD Control

on:
  pull_request:
    branches: ["master", "staging", "main"]
  push:
    branches: ["v-*"]

permissions:
  contents: read

env:
  LINT_PATH: ${{ vars.LINT_PATH }}
  PYPI_PWD: ${{ secrets.PYPI_PWD }}
  PYPI_USER: ${{ secrets.PYPI_USER }}

jobs:
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 in test
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install test dependencies
        run: |
          make install_pkg
      - name: Pytest
        run: |
          make test
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 in lint
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install lint dependencies
        run: |
          make install_pkg
      - name: Lint src
        run: |
          make lint
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]

    if: contains(github.ref, 'refs/heads/v-')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install poetry
        run: |
          make install_poetry
      - name: Build package
        run: |
          make build_src
      - name: Publish package
        run: |
          make publish